### ISSUE TITLE
Is there a way to configure the server via api/cli?

### ISSUE THREAD

**Issue by gmatuz** [MythicC2Profiles/http#2]
could not really find a config option for this or something that would describe the API

**Comment by gmatuz** [comment]
Found my answer: https://docs.mythic-c2.net/customizing/c2-related-development/c2-profile-code/server-side-coding/c2-configuration-files
you can directly write this file (not sure how you apply it)

also there are endpoints `/api/v1.4/c2profile_upload_file_webhook` and  `/api/v1.4/start_stop_profile_webhook`

**Comment by its-a-feature** [comment]
Hey! Great question. I don't currently have anything built in that does it, but you found the relevant pieces anyway. By simply writing to that `config.json` file within the C2 Profile container, the updates are automatically reflected inside of the container. To "apply" them, you'd simply need to stop the profile and start it again (via that start_stop_profile_webhook) so that the `server` code in the profile can read in the changes to the config file and apply them
