### ISSUE TITLE
Ssl Letsencrypt

### ISSUE THREAD

**Issue by Chomikmarkus** [MythicC2Profiles/http#3]
Hello!
Tried to configure http C2_Profile use ssl with Letsencrypt! Getting error that cannot find keys! 
Tried inside /etc/letsencrypt/live/somesite.com/ 
directory!
Tried also to copy keys into C2_Profile directory still keys not found!

**Comment by its-a-feature** [comment]
Good question! 

All of the c2 profiles run in their own Docker containers, which is why I think you're having issues with paths. Take your private key and cert and put them in `Mythic/C2_Profiles/http/c2_code/`. Let's say you called them "key.pem" and "key.cert". In the `config.json` file that's in that same folder (or through the configure button in the web UI), update the two key paths to just the names `key.pem` and `key.cert`. Now, when you click to start the profile, after a few seconds you should get a message saying that SSL was successfully started on the specified port.  Also make sure you put `use_ssl` to `true` (https://github.com/MythicC2Profiles/http/blob/master/C2_Profiles/http/c2_code/config.json#L15)

**Comment by Chomikmarkus** [comment]
Exactly what i did!

**Comment by Chomikmarkus** [comment]
![Screenshot_20211228-204223](https://user-images.githubusercontent.com/92059377/147597109-50380b31-5c97-4f02-8235-ff696cc63d0b.png)
![Screenshot_20211228-204039](https://user-images.githubusercontent.com/92059377/147597114-edd4ca99-cc85-45cd-9061-713a5b4ceacc.png)
![Screenshot_20211228-204112](https://user-images.githubusercontent.com/92059377/147597115-0f4d3069-26df-43e1-aae8-4d035b80735c.png)

**Comment by its-a-feature** [comment]
If your screenshot is accurate, then your cert_path value is `: /fullchain.pem"` which isn't valid syntax, hence the error. it should be `: "fullchain.pem"`

**Comment by Chomikmarkus** [comment]
I saw that fixed it and same error

**Comment by Chomikmarkus** [comment]
![Screenshot_20211228-205527](https://user-images.githubusercontent.com/92059377/147598060-8f36fbb5-a2cd-478a-ad10-a3b29eb7f78e.png)
![Screenshot_20211228-205557](https://user-images.githubusercontent.com/92059377/147598062-7745e41f-7d7e-4908-aafc-8a64c45977a1.png)

**Comment by its-a-feature** [comment]
Well, now it's a different error saying it can't be found. What are the permissions on the `fullchain.pem` and `privkey.pem`. I wonder if they're not readable by the container?

**Comment by Chomikmarkus** [comment]
Actually this was problem after moving .pem keys from letsencrypt folder they became unreadable! i generated keys with openssl and everything works fine!
